live_config_reload = true

[colors.bright]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.cursor]
cursor = "#bb9af7"
text = "#1a1b26"

[colors.normal]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14

[font.bold]
family = "IosevkaTerm Nerd Font"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"

[font.italic]
family = "IosevkaTerm Nerd Font"

[font.normal]
family = "IosevkaTerm Nerd Font"

[selection]
save_to_clipboard = false

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 0.9

[window.padding]
x = 10
y = 5
